#!/usr/bin/env python3
"""
打包构建脚本 — 使用 PyInstaller 将 mvp_tests 打包为 Windows 独立安装包。

用法:
    python build_installer.py           # 默认构建 (目录模式)
    python build_installer.py --clean   # 清理后重新构建
    python build_installer.py -h        # 查看帮助

输出:
    dist/展会目录PDF提取工具/
    ├── 展会目录PDF提取工具.exe        # 主程序
    ├── config.yaml                    # 默认配置 (如存在)
    ├── field_templates.json           # 默认字段模板 (如存在)
    ├── _internal/                     # Python运行时+依赖库
    └── 启动.bat                       # 备用启动脚本
"""

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


PROJECT_DIR = Path(__file__).parent.resolve()
DIST_DIR = PROJECT_DIR / "dist"
APP_NAME = "展会目录PDF提取工具"
BUILD_DIR = PROJECT_DIR / "build_installer_temp"


def find_paddleocr_models():
    """Locate PaddleOCR model files that need to be bundled."""
    home = Path.home()
    paddle_home = home / ".paddleocr"
    if not paddle_home.exists():
        # Check alternate locations
        for alt in [
            Path(os.environ.get("PADDLEOCR_HOME", "")),
            Path.home() / "AppData" / "Local" / ".paddleocr",
        ]:
            if alt.exists():
                paddle_home = alt
                break

    if not paddle_home.exists():
        print("[WARN] PaddleOCR models not found at ~/.paddleocr")
        return []

    additions = []
    for root, dirs, files in os.walk(paddle_home):
        for f in files:
            src = os.path.join(root, f)
            rel = os.path.relpath(src, paddle_home)
            # PyInstaller data format: (source_path, dest_dir_in_bundle)
            additions.append((src, os.path.join(".paddleocr", os.path.dirname(rel))))
    print(f"[INFO] Found {len(additions)} PaddleOCR model files")
    return additions


def write_spec_file(data_additions: list) -> Path:
    """Generate the PyInstaller .spec file."""
    # Build the datas list for the spec
    datas_entries = []
    for src, dest in data_additions:
        # Format: ('source_path', 'dest_dir')
        datas_entries.append(f"    ('{src.replace(chr(92), chr(92)+chr(92))}', '{dest.replace(chr(92), '/')}'),")

    datas_block = "[\n" + "\n".join(datas_entries[:3]) + "\n    # ... (model files)\n]" if len(datas_entries) > 3 else "[]"

    spec_content = f'''# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for 展会目录PDF提取工具
Generated by build_installer.py
"""
import sys
from pathlib import Path

# Add project root to path so hidden imports resolve
PROJECT_DIR = r"{str(PROJECT_DIR)}"
sys.path.insert(0, PROJECT_DIR)

a = Analysis(
    [os.path.join(PROJECT_DIR, "gui_app.py")],
    pathex=[PROJECT_DIR],
    binaries=[],
    datas={datas_block},
    hiddenimports=[
        # PDF
        "fitz",
        # OCR
        "paddleocr", "paddle",
        "paddle.fluid", "paddle.fluid.core",
        "paddle.incubate",
        # Image processing
        "cv2", "PIL", "PIL.Image", "PIL.ImageTk",
        "PIL.ImageDraw", "PIL.ImageFont",
        # Step modules
        "step1_pdf_parse", "step2_layout_analysis",
        "step3_field_extraction", "step4_image_matching",
        "step5_e2e_pipeline",
        "ocr_engine",
        # Data processing
        "openpyxl", "pandas", "yaml",
        "json", "re", "hashlib", "io",
        "threading", "queue", "collections",
        # Tkinter
        "tkinter", "tkinter.ttk", "tkinter.filedialog",
        "tkinter.messagebox", "tkinter.scrolledtext",
        # Paddle sub-modules
        "paddle.nn", "paddle.nn.functional",
        "paddle.tensor", "paddle.io",
        "paddle.device", "paddle.framework",
        "paddle.static",
        # Additional PaddleOCR internals
        "paddleocr.tools.infer",
        "paddleocr.ppocr",
        "paddleocr.ppocr.utils",
        "paddleocr.ppocr.postprocess",
        "skimage", "skimage.morphology",
        "scipy", "scipy.ndimage",
        "imghdr", "shapely",
        "lanms", "lanms-neo",
        "pyclipper",
        "attrdict",
        "rapidfuzz",
        "filelock",
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
        "matplotlib", "jupyter", "IPython",
        "notebook", "nbconvert", "nbformat",
        "ipykernel", "jupyter_client",
        "tornado", "pygments", "prompt_toolkit",
        "sqlalchemy", "alembic",
        "pytest", "setuptools", "pip",
        "tkinter.test",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

# Filter to remove duplicate Tcl/Tk binaries
import re as _re
_tcl_dll = _re.compile(r'tcl8\\.dll|tk8\\.dll|tcl86t\\.dll|tk86t\\.dll', _re.IGNORECASE)
_seen_tcl = set()
_filtered_binaries = []
for b in a.binaries:
    name = b[0]
    if _tcl_dll.match(name):
        if name in _seen_tcl:
            continue
        _seen_tcl.add(name)
    _filtered_binaries.append(b)

a.binaries = _filtered_binaries

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="{APP_NAME}",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="{APP_NAME}",
)
'''
    spec_path = PROJECT_DIR / f"{APP_NAME}.spec"
    with open(spec_path, "w", encoding="utf-8") as f:
        f.write(spec_content)
    return spec_path


def copy_extra_files(dist_dir: Path):
    """Copy additional runtime files to the distribution directory."""
    # Configuration files
    for cfg_file in ["config.yaml", "field_templates.json"]:
        src = PROJECT_DIR / cfg_file
        if src.exists():
            dst = dist_dir / cfg_file
            shutil.copy2(src, dst)
            print(f"[INFO] Copied {cfg_file}")

    # Create launcher batch file
    bat_content = f'''@echo off
chcp 65001 >nul
title {APP_NAME}
echo 正在启动 {APP_NAME}...
echo.
if not exist "_internal" (
    echo [错误] 未找到 _internal 目录，请确保已解压完整安装包。
    pause
    exit /b 1
)
start "" "{APP_NAME}.exe"
'''
    bat_path = dist_dir / "启动.bat"
    with open(bat_path, "w", encoding="utf-8") as f:
        f.write(bat_content)
    print(f"[INFO] Created 启动.bat")


def main():
    parser = argparse.ArgumentParser(description="打包构建脚本")
    parser.add_argument("--clean", action="store_true", help="清理旧的构建产物")
    parser.add_argument("--no-models", action="store_true", help="不打包PaddleOCR模型文件（减小体积，但首次运行需下载）")
    args = parser.parse_args()

    # Clean if requested
    if args.clean:
        for d in [DIST_DIR / APP_NAME, BUILD_DIR]:
            if d.exists():
                shutil.rmtree(d)
                print(f"[INFO] Cleaned {d}")
        spec = PROJECT_DIR / f"{APP_NAME}.spec"
        if spec.exists():
            spec.unlink()
        print("[INFO] Clean completed")

    # Gather PaddleOCR models
    data_files = []
    if not args.no_models:
        data_files = find_paddleocr_models()
    else:
        print("[INFO] Skipping model files — will be downloaded at first run")

    # Write spec file (with minimal datas, models are large so we handle separately)
    # Actually, for simplicity, let's pass model files directly to PyInstaller CLI
    spec_path = PROJECT_DIR / f"{APP_NAME}.spec"

    # Build add-data arguments for PyInstaller CLI
    add_data_args = []
    for src, dest in data_files:
        add_data_args.extend(["--add-data", f"{src}{os.pathsep}{dest}"])

    # Include local config/template files
    for cfg in ["config.yaml", "field_templates.json"]:
        cfg_path = PROJECT_DIR / cfg
        if cfg_path.exists():
            add_data_args.extend(["--add-data", f"{cfg_path}{os.pathsep}."])

    # Build PyInstaller command
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onedir",
        "--name", APP_NAME,
        "--distpath", str(DIST_DIR),
        "--workpath", str(BUILD_DIR),
        "--noconfirm",
        "--clean" if args.clean else "",
        "--noconsole",  # GUI app, no console window
        "--hidden-import", "fitz",
        "--hidden-import", "paddleocr",
        "--hidden-import", "paddle",
        "--hidden-import", "cv2",
        "--hidden-import", "PIL",
        "--hidden-import", "PIL.Image",
        "--hidden-import", "PIL.ImageTk",
        "--hidden-import", "step1_pdf_parse",
        "--hidden-import", "step2_layout_analysis",
        "--hidden-import", "step3_field_extraction",
        "--hidden-import", "step4_image_matching",
        "--hidden-import", "step5_e2e_pipeline",
        "--hidden-import", "ocr_engine",
        "--hidden-import", "openpyxl",
        "--hidden-import", "yaml",
        "--hidden-import", "tkinter",
        "--hidden-import", "tkinter.ttk",
        "--hidden-import", "tkinter.filedialog",
        "--hidden-import", "tkinter.messagebox",
        "--hidden-import", "rapidfuzz",
        "--hidden-import", "pyclipper",
        "--hidden-import", "shapely",
        "--hidden-import", "skimage",
        "--hidden-import", "skimage.morphology",
        "--hidden-import", "scipy.ndimage",
        "--hidden-import", "attrdict",
        "--hidden-import", "filelock",
        "--exclude-module", "matplotlib",
        "--exclude-module", "jupyter",
        "--exclude-module", "IPython",
        "--exclude-module", "pytest",
        "--exclude-module", "setuptools",
        "--exclude-module", "pip",
        str(PROJECT_DIR / "gui_app.py"),
    ]
    # Filter out empty strings
    cmd = [c for c in cmd if c]
    # Add data files
    cmd = cmd[:3] + add_data_args + cmd[3:]

    print(f"[INFO] Building {APP_NAME}...")
    print(f"[INFO] This may take 5-15 minutes on first run.")
    print(f"[INFO] Command: {' '.join(cmd[:8])} ...")

    result = subprocess.run(cmd, cwd=str(PROJECT_DIR))
    if result.returncode != 0:
        print(f"\n[ERROR] PyInstaller build failed with code {result.returncode}")
        sys.exit(1)

    # Post-build: copy extras
    dist_dir = DIST_DIR / APP_NAME
    if dist_dir.exists():
        copy_extra_files(dist_dir)

        # Calculate size
        total_size = sum(
            os.path.getsize(os.path.join(dp, f))
            for dp, dn, fn in os.walk(dist_dir) for f in fn
        )
        print(f"\n{'='*60}")
        print(f"  构建完成!")
        print(f"  输出目录: {dist_dir}")
        print(f"  总大小:   {total_size / (1024*1024):.0f} MB")
        print(f"  启动方式: 双击 {APP_NAME}.exe 或 启动.bat")
        print(f"{'='*60}")
    else:
        print(f"\n[ERROR] Build output not found at {dist_dir}")
        sys.exit(1)


if __name__ == "__main__":
    main()
